# Generated by Django 4.2.14 on 2024-07-19 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TestModel", "0002_book_contact_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("age", models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="AuthorDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.SmallIntegerField(choices=[(0, "女"), (1, "男"), (2, "保密")]),
                ),
                ("tel", models.CharField(max_length=32)),
                ("addr", models.CharField(max_length=64)),
                ("birthday", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Publish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("city", models.CharField(max_length=64)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name="tag",
            name="contact",
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.AddField(
            model_name="author",
            name="au_detail",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="TestModel.authordetail"
            ),
        ),
    ]
