# Generated by Django 4.2.14 on 2024-07-19 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TestModel", "0003_author_authordetail_publish_remove_tag_contact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(to="TestModel.author"),
        ),
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="publish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="TestModel.publish"
            ),
        ),
    ]
