# Generated by Django 4.2.14 on 2024-07-19 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("TestModel", "0004_book_authors_alter_book_id_alter_book_publish"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Emp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("age", models.IntegerField()),
                ("salary", models.DecimalField(decimal_places=2, max_digits=8)),
                ("dep", models.CharField(max_length=32)),
                ("province", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Emps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("age", models.IntegerField()),
                ("salary", models.DecimalField(decimal_places=2, max_digits=8)),
                ("province", models.CharField(max_length=32)),
                (
                    "dep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="TestModel.dep"
                    ),
                ),
            ],
        ),
    ]
